export type StylePairing = {
  item: string;
  reason: string;
};

export type Product = {
  id: number;
  name: string;
  category: string;
  subcategory: string;
  price: number;
  size: string;          // single fixed size — one of one
  waist?: string;        // fixed waist e.g. 'W32"' or elastic range e.g. 'W28"–34"'
  length?: string;       // inseam/outseam length e.g. 'L30"'
  elasticWaist?: boolean; // true = stretchy/drawstring waist
  colours: string[];
  tag: "NEW" | "2 LEFT" | "1 LEFT" | "SOLD" | "ESSENTIAL" | "STAFF PICK" | "";
  image: string;         // primary image
  images?: string[];     // additional images (for scrollable gallery)
  description: string;
  available: boolean;
  pairsWith: StylePairing[];  // suggested items to pair with
};

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Inter Milan Lautaro #10 Jersey",
    category: "Clothing",
    subcategory: "T-shirts",
    price: 14500,
    size: "L",
    colours: ["Blue", "Black"],
    tag: "NEW",
    image: "/products/lautaro inter milan jersey.jpeg",
    description: "Iconic Inter Milan home jersey featuring Lautaro Martínez #10. Python-print design, Lenovo sponsor. Good-as-new condition.",
    available: true,
    pairsWith: [
      { item: "Black Baggy Jeans", reason: "The contrast between the bold blue jersey and black denim keeps the fit clean and grounded." },
      { item: "Grey Acid Wash Sweatpants", reason: "A relaxed, tonal pairing. Grey neutralises the jersey's colour without competing with it." },
      { item: "Adidas × FOG Sneakers", reason: "Chunky white sneakers add weight to the bottom of the fit and balance the oversized jersey top." },
    ],
  },
  {
    id: 2,
    name: "Liverpool FC 2006 Jersey",
    category: "Clothing",
    subcategory: "T-shirts",
    price: 12500,
    size: "M",
    colours: ["Red", "White"],
    tag: "2 LEFT",
    image: "/products/liverpool 2006 jersey.jpeg",
    description: "Classic Liverpool FC 2006 home kit. Adidas. Carlsberg sponsor. A collector's piece in great condition.",
    available: true,
    pairsWith: [
      { item: "Black Baggy Jeans", reason: "Black denim lets the red jersey do the talking. A timeless combo." },
      { item: "Black Sweatpants", reason: "Keeps the vibe relaxed and street-ready — jersey as a statement piece." },
      { item: "Vintage Puma Cap", reason: "The red cap pulls colour from the jersey and ties the whole look together." },
    ],
  },
  {
    id: 3,
    name: "Burgundy Vintage Windbreaker",
    category: "Clothing",
    subcategory: "Jackets",
    price: 18000,
    size: "M",
    colours: ["Burgundy", "White", "Blue"],
    tag: "NEW",
    image: "/products/burgundy wind breaker jacket.jpeg",
    description: "Retro Nassau windbreaker in bold burgundy. Striking graphic panelling, full zip, lightweight feel. Perfect for the drop.",
    available: true,
    pairsWith: [
      { item: "Black Baggy Jeans", reason: "Burgundy over black is a classic contrast — the baggier the jeans, the better the silhouette." },
      { item: "Navy Stripe Oversized Tee", reason: "Layer the tee underneath with it slightly visible at the hem for that 90s layering look." },
      { item: "Adidas × FOG Sneakers", reason: "The clean white sneaker base grounds the bold jacket colour palette." },
    ],
  },
  {
    id: 4,
    name: "Bomber Jacket",
    category: "Clothing",
    subcategory: "Jackets",
    price: 16500,
    size: "L",
    colours: ["Black"],
    tag: "NEW",
    image: "/products/bomber jacket.jpeg",
    description: "Clean, minimal bomber. Streetwear staple. Versatile enough for any fit.",
    available: true,
    pairsWith: [
      { item: "Navy Stripe Oversized Tee", reason: "The stripe tee adds visual interest under the bomber without breaking the clean black palette." },
      { item: "Black Baggy Jeans", reason: "Full black monochrome. Simple, sharp, and effective." },
      { item: "Pink MLB Cap", reason: "A pop of pink cuts through the all-black and adds personality to the fit." },
    ],
  },
  {
    id: 5,
    name: "Navy Blue Quarter-Zip Sweatshirt",
    category: "Clothing",
    subcategory: "Track suits",
    price: 13500,
    size: "M",
    colours: ["Navy", "White"],
    tag: "1 LEFT",
    image: "/products/navy blue sweatshirt.jpeg",
    description: "Outlier 1991 RC Rider Supply Co. quarter-zip. Navy/white colourblock. Collegiate aesthetic. One left — move fast.",
    available: true,
    pairsWith: [
      { item: "Blue Jeans", reason: "Tonal navy-on-blue denim is a smart, understated pairing with a collegiate edge." },
      { item: "Black Baggy Jeans", reason: "The dark contrast between navy top and black jeans keeps the look clean and structured." },
      { item: "Adidas × FOG Sneakers", reason: "White sneakers lift the navy colour and keep the collegiate energy going." },
    ],
  },
  {
    id: 6,
    name: "Light Grey Sweatshirt",
    category: "Clothing",
    subcategory: "Track suits",
    price: 12000,
    size: "S",
    colours: ["Grey"],
    tag: "NEW",
    image: "/products/light grey sweatshirt.jpeg",
    description: "Relaxed-fit light grey crewneck. Everyday comfort, clean silhouette.",
    available: true,
    pairsWith: [
      { item: "Black Baggy Jeans", reason: "A grey/black combo is the most versatile everyday fit — it always works." },
      { item: "Grey Acid Wash Sweatpants", reason: "Tonal grey matching top and bottom for that clean, intentional streetwear look." },
      { item: "Vintage Puma Cap", reason: "The red cap pops against grey for a confident colour accent." },
    ],
  },
  {
    id: 7,
    name: "Classic Polo Shirt",
    category: "Clothing",
    subcategory: "Shirts",
    price: 9000,
    size: "L",
    colours: ["White"],
    tag: "NEW",
    image: "/products/polo shirt.jpeg",
    description: "Crisp polo shirt. Timeless cut. Great for layering or wearing standalone.",
    available: true,
    pairsWith: [
      { item: "Blue Jeans", reason: "White polo and blue denim is a classic smart-casual combination that never ages." },
      { item: "Black Baggy Jeans", reason: "White over black is sharp — the polo tucks for a cleaner look or worn loose for streetwear." },
      { item: "Adidas × FOG Sneakers", reason: "The chunky white sneakers match the polo's clean white and elevate the full look." },
    ],
  },
  {
    id: 8,
    name: "Navy Stripe Oversized Tee",
    category: "Clothing",
    subcategory: "T-shirts",
    price: 7500,
    size: "XL",
    colours: ["Navy", "White"],
    tag: "NEW",
    image: "/products/Stripe t-shirt.jpeg",
    description: "Boxy navy/white stripe tee. Heavy cotton. Worn oversized or tucked — both work.",
    available: true,
    pairsWith: [
      { item: "Black Baggy Jeans", reason: "The stripe tee is a statement on its own — let the black jeans stay out of the way." },
      { item: "Grey Acid Wash Sweatpants", reason: "Relaxed tee with relaxed sweats. Laid-back energy, intentional look." },
      { item: "Pink MLB Cap", reason: "A soft pink cap adds warmth and contrast to the cool navy/white stripe palette." },
    ],
  },
  {
    id: 9,
    name: "Red Casual Shorts",
    category: "Clothing",
    subcategory: "Shorts",
    price: 6500,
    size: "M",
    waist: 'W32"',
    length: 'L19"',
    colours: ["Red"],
    tag: "NEW",
    image: "/products/red casual short.jpeg",
    description: "Easy-wearing red shorts. Comfortable fit. Perfect for warmer days.",
    available: true,
    pairsWith: [
      { item: "Navy Stripe Oversized Tee", reason: "The stripe tee's navy picks up on the red shorts' boldness for a colour-blocked summer look." },
      { item: "Classic Polo Shirt", reason: "White polo and red shorts is a clean, sporty combination." },
      { item: "Adidas × FOG Sneakers", reason: "White chunky sneakers complete the bold colour scheme without adding more colour." },
    ],
  },
  {
    id: 10,
    name: "White Casual Shorts",
    category: "Clothing",
    subcategory: "Shorts",
    price: 6500,
    size: "S",
    waist: 'W28"',
    length: 'L18"',
    colours: ["White"],
    tag: "NEW",
    image: "/products/white casual short.jpeg",
    description: "Minimal white shorts. Clean look. Pairs with everything.",
    available: true,
    pairsWith: [
      { item: "Inter Milan Lautaro #10 Jersey", reason: "White shorts let the jersey pop without competition. Classic football-inspired look." },
      { item: "Light Grey Sweatshirt", reason: "White and grey is effortlessly minimal — an easy go-to pairing." },
      { item: "Vintage Puma Cap", reason: "The red cap adds colour to the all-white/grey outfit and finishes it off." },
    ],
  },
  {
    id: 11,
    name: "Black Baggy Jeans",
    category: "Clothing",
    subcategory: "Jeans",
    price: 15000,
    size: "32",
    waist: 'W32"',
    length: 'L30"',
    colours: ["Black"],
    tag: "NEW",
    image: "/products/black baggy jeans.jpeg",
    description: "Wide-leg black denim with a relaxed, barrel-leg silhouette. Drawstring hem. Statement piece.",
    available: true,
    pairsWith: [
      { item: "Burgundy Vintage Windbreaker", reason: "The bold jacket over clean black denim is a textbook streetwear combination." },
      { item: "Bomber Jacket", reason: "All-black top and bottom with a bomber creates a sleek, put-together silhouette." },
      { item: "Adidas × FOG Sneakers", reason: "Chunky white sneakers under baggy black jeans creates the perfect proportional contrast." },
    ],
  },
  {
    id: 12,
    name: "Blue Jeans",
    category: "Clothing",
    subcategory: "Jeans",
    price: 13000,
    size: "32",
    waist: 'W32"',
    length: 'L30"',
    colours: ["Blue"],
    tag: "NEW",
    image: "/products/blue jeans.jpeg",
    description: "Classic blue denim. Straight fit. Goes with everything in the wardrobe.",
    available: true,
    pairsWith: [
      { item: "Classic Polo Shirt", reason: "White polo and blue jeans is timeless. Smart, clean, and versatile." },
      { item: "Navy Blue Quarter-Zip Sweatshirt", reason: "Tonal navy and denim blue is a cohesive, put-together look." },
      { item: "Adidas × FOG Sneakers", reason: "Chunky sneakers with straight blue denim creates a modern silhouette." },
    ],
  },
  {
    id: 13,
    name: "Black Sweatpants",
    category: "Clothing",
    subcategory: "Sweatpants",
    price: 9000,
    size: "L",
    waist: 'W30"–38"',
    length: 'L30"',
    elasticWaist: true,
    colours: ["Black"],
    tag: "NEW",
    image: "/products/black sweatpants.jpeg",
    description: "Essential black sweatpants. Drawstring elastic waist. Comfortable, relaxed fit for everyday wear.",
    available: true,
    pairsWith: [
      { item: "Liverpool FC 2006 Jersey", reason: "Red jersey over black sweats is easy and expressive — a classic combination." },
      { item: "Light Grey Sweatshirt", reason: "Grey top and black bottoms is the foundation of a clean athleisure look." },
      { item: "Vintage Puma Cap", reason: "The red cap adds a colour punch to a neutral black-and-grey outfit." },
    ],
  },
  {
    id: 14,
    name: "Grey Acid Wash Sweatpants",
    category: "Clothing",
    subcategory: "Sweatpants",
    price: 9500,
    size: "M",
    waist: 'W28"–36"',
    length: 'L29"',
    elasticWaist: true,
    colours: ["Grey"],
    tag: "NEW",
    image: "/products/greys weatpants.jpeg",
    description: "Washed grey sweatpants with a vintage, faded look. Wide leg. Drawstring elastic waist.",
    available: true,
    pairsWith: [
      { item: "Inter Milan Lautaro #10 Jersey", reason: "The washed grey tones down the jersey's colour intensity for a balanced, relaxed look." },
      { item: "Light Grey Sweatshirt", reason: "Full grey co-ord. When tones match, the intentionality comes through." },
      { item: "Adidas × FOG Sneakers", reason: "White sneakers under grey washed sweats lifts the overall look." },
    ],
  },
  {
    id: 15,
    name: "Vintage Puma Cap",
    category: "Accessories",
    subcategory: "Caps and hats",
    price: 5000,
    size: "One Size",
    colours: ["Red"],
    tag: "NEW",
    image: "/products/puma cap.jpeg",
    description: "Vintage Puma 6-panel cap in red corduroy. Original tags still on. Rare find.",
    available: true,
    pairsWith: [
      { item: "Light Grey Sweatshirt", reason: "The red cap pops against grey and adds the finishing colour accent the outfit needs." },
      { item: "Black Sweatpants", reason: "Red cap over a neutral fit injects personality without changing the whole vibe." },
      { item: "Navy Stripe Oversized Tee", reason: "The warmth of the red cap contrasts nicely with the cool navy/white stripe palette." },
    ],
  },
  {
    id: 16,
    name: "Pink MLB Cap",
    category: "Accessories",
    subcategory: "Caps and hats",
    price: 5500,
    size: "One Size",
    colours: ["Pink"],
    tag: "NEW",
    image: "/products/pink MLB cap.jpeg",
    description: "MLB-style pink cap. Clean embroidery. Adjustable strap.",
    available: true,
    pairsWith: [
      { item: "Bomber Jacket", reason: "Pink against all-black adds an unexpected but intentional pop of colour." },
      { item: "Navy Stripe Oversized Tee", reason: "The softness of pink plays off the bold navy/white stripe for a balanced look." },
      { item: "White Casual Shorts", reason: "White shorts keep the focus upward on the colourful cap and top." },
    ],
  },
  {
    id: 17,
    name: "Adidas × FOG Sneakers",
    category: "Shoes",
    subcategory: "Sneakers",
    price: 28000,
    size: "42",
    colours: ["White", "Grey"],
    tag: "NEW",
    image: "/products/adidas x fog sneakers.jpeg",
    description: "Adidas Fear of God collaboration. Chunky sole, premium materials. Limited and hard to find.",
    available: true,
    pairsWith: [
      { item: "Black Baggy Jeans", reason: "The contrast between the white chunky sole and black denim is one of the best sneaker pairings in streetwear." },
      { item: "Grey Acid Wash Sweatpants", reason: "Wide leg sweats and chunky sneakers are made for each other — proportions are perfect." },
      { item: "Navy Blue Quarter-Zip Sweatshirt", reason: "The white base of the sneakers picks up the white panels in the quarter-zip for a cohesive look." },
    ],
  },
  {
    id: 18,
    name: "Baggy Flared Sweatpants in Grey",
    category: "Clothing",
    subcategory: "Sweatpants",
    price: 10500,
    size: "M",
    waist: 'W28"–36"',
    length: 'L31"',
    elasticWaist: true,
    colours: ["Grey"],
    tag: "NEW",
    image: "/products/Baggy flared sweatpants in grey.jpeg",
    description: "Wide-leg flared sweatpants in grey. Drawstring elastic waist. A statement silhouette with effortless comfort.",
    available: true,
    pairsWith: [
      { item: "Light Grey Sweatshirt", reason: "Full grey co-ord with a flared leg. Intentional and clean." },
      { item: "Inter Milan Lautaro #10 Jersey", reason: "Bold jersey over flared sweats — streetwear energy, top to bottom." },
      { item: "Adidas × FOG Sneakers", reason: "Chunky sneakers peek out under the flare for the perfect finish." },
    ],
  },
  {
    id: 19,
    name: "Baggy Blue Jeans",
    category: "Clothing",
    subcategory: "Jeans",
    price: 14000,
    size: "32",
    waist: 'W32"',
    length: 'L30"',
    colours: ["Blue"],
    tag: "NEW",
    image: "/products/Baggy jeans blue.jpeg",
    description: "Relaxed baggy blue denim. Wide-leg fit with a worn-in wash. A versatile drop essential.",
    available: true,
    pairsWith: [
      { item: "Classic Polo Shirt", reason: "Baggy jeans and a polo is a timeless smart-casual combination." },
      { item: "Burgundy Vintage Windbreaker", reason: "The bold jacket over loose blue denim is a textbook 90s layering move." },
      { item: "Adidas × FOG Sneakers", reason: "Chunky sneakers under baggy denim — the silhouette speaks for itself." },
    ],
  },
  {
    id: 20,
    name: "Brown Leather Jacket (M)",
    category: "Clothing",
    subcategory: "Jackets",
    price: 32000,
    size: "M",
    colours: ["Brown"],
    tag: "NEW",
    image: "/products/Brown leather jacket - M.jpeg",
    description: "Genuine brown leather jacket. Clean minimal cut. A rare thrift find in excellent condition.",
    available: true,
    pairsWith: [
      { item: "Black Baggy Jeans", reason: "Brown leather over black denim is one of the most timeless combinations in menswear." },
      { item: "Navy Stripe Oversized Tee", reason: "The casual tee softens the jacket for a relaxed but put-together look." },
      { item: "Adidas × FOG Sneakers", reason: "White chunky sneakers modernise the leather jacket and keep it street-ready." },
    ],
  },
  {
    id: 21,
    name: "Brown Leather Jacket (L–XL)",
    category: "Clothing",
    subcategory: "Jackets",
    price: 32000,
    size: "L–XL",
    colours: ["Brown"],
    tag: "NEW",
    image: "/products/Brown leather jacket L-XL.jpeg",
    description: "Genuine brown leather jacket in a larger cut. Relaxed oversized fit. Premium condition — a serious find.",
    available: true,
    pairsWith: [
      { item: "Black Baggy Jeans", reason: "Brown leather over black denim is one of the most timeless combinations in menswear." },
      { item: "Blue Jeans", reason: "Classic blue denim lets the leather jacket take centre stage." },
      { item: "Adidas × FOG Sneakers", reason: "White chunky sneakers modernise the leather jacket and keep it street-ready." },
    ],
  },
  {
    id: 22,
    name: "Celtics Basketball Jersey",
    category: "Clothing",
    subcategory: "T-shirts",
    price: 13000,
    size: "L",
    colours: ["Green", "White"],
    tag: "NEW",
    image: "/products/Celtics basketball jersey.jpeg",
    description: "Boston Celtics NBA basketball jersey. Classic green colourway. Great condition.",
    available: true,
    pairsWith: [
      { item: "Black Baggy Jeans", reason: "The green jersey pops over black denim — clean contrast, no competition." },
      { item: "Black Sweatpants", reason: "Jersey and sweats is the quintessential relaxed streetwear combination." },
      { item: "Adidas × FOG Sneakers", reason: "White sneakers pick up the jersey's white accents and complete the look." },
    ],
  },
  {
    id: 23,
    name: "Graphic Camo Cap in Red",
    category: "Accessories",
    subcategory: "Caps and hats",
    price: 5500,
    size: "One Size",
    colours: ["Red", "Camo"],
    tag: "NEW",
    image: "/products/Graphic camo cap in red.jpeg",
    description: "Bold red camo graphic cap. Six-panel structured fit. Adjustable strap. A statement accessory.",
    available: true,
    pairsWith: [
      { item: "Black Baggy Jeans", reason: "The bold cap over a simple black fit lets the accessory do all the talking." },
      { item: "Navy Stripe Oversized Tee", reason: "Red camo cap with a navy/white stripe tee — colour-blocked and intentional." },
      { item: "Bomber Jacket", reason: "The graphic cap breaks up the clean all-black bomber outfit perfectly." },
    ],
  },
  {
    id: 24,
    name: "Graphic T-Shirt in Smoke",
    category: "Clothing",
    subcategory: "T-shirts",
    price: 8000,
    size: "L",
    colours: ["Grey", "Black"],
    tag: "NEW",
    image: "/products/Graphic t-shirt in smoke.jpeg",
    description: "Oversized graphic tee in a smoked grey wash. Heavy cotton. Worn-in feel from day one.",
    available: true,
    pairsWith: [
      { item: "Black Baggy Jeans", reason: "Smoke tee over black denim — a washed, muted palette that works every time." },
      { item: "Grey Acid Wash Sweatpants", reason: "Tonal grey-on-grey with different textures. Understated and intentional." },
      { item: "Vintage Puma Cap", reason: "The red cap cuts through the muted palette and adds the finishing touch." },
    ],
  },
  {
    id: 25,
    name: "Graphic White T-Shirt",
    category: "Clothing",
    subcategory: "T-shirts",
    price: 7500,
    size: "M",
    colours: ["White"],
    tag: "NEW",
    image: "/products/Graphic white t-shirt.jpeg",
    description: "Clean white graphic tee. Boxy fit. A versatile base layer or standalone statement.",
    available: true,
    pairsWith: [
      { item: "Black Baggy Jeans", reason: "White tee and black jeans is the most dependable fit in streetwear." },
      { item: "Bomber Jacket", reason: "White graphic tee layered under a black bomber — sharp and easy." },
      { item: "Blue Jeans", reason: "White over blue denim is a classic that never ages." },
    ],
  },
  {
    id: 26,
    name: "Puffy Gilet in Navy Blue",
    category: "Clothing",
    subcategory: "Jackets",
    price: 15000,
    size: "L",
    colours: ["Navy"],
    tag: "NEW",
    image: "/products/Puffy gilet in navy blue.jpeg",
    description: "Quilted navy puffer gilet. Lightweight and warm. Perfect for layering over tees or hoodies.",
    available: true,
    pairsWith: [
      { item: "Navy Stripe Oversized Tee", reason: "Layer the gilet over the tee for a tonal navy look with added depth." },
      { item: "Black Baggy Jeans", reason: "Navy gilet over black denim is clean and versatile — a go-to combo." },
      { item: "Adidas × FOG Sneakers", reason: "Chunky white sneakers ground the layered navy look." },
    ],
  },
  {
    id: 27,
    name: "Realtree Ushanka Trapper Hat",
    category: "Accessories",
    subcategory: "Caps and hats",
    price: 8000,
    size: "One Size",
    colours: ["Camo", "Brown"],
    tag: "NEW",
    image: "/products/Realtree ushanka : trapper hat.jpeg",
    description: "Realtree camo ushanka trapper hat. Faux fur lining. Ear flaps. A statement winter piece.",
    available: true,
    pairsWith: [
      { item: "Bomber Jacket", reason: "Camo trapper over a black bomber is an unexpected but striking layered look." },
      { item: "Brown Leather Jacket (L–XL)", reason: "Earth tones head to toe — the camo hat and brown leather are made for each other." },
      { item: "Black Baggy Jeans", reason: "The statement hat does the heavy lifting — keep the bottom simple with black denim." },
    ],
  },
  {
    id: 28,
    name: "Short Sleeve Shirt",
    category: "Clothing",
    subcategory: "Shirts",
    price: 8500,
    size: "L",
    colours: ["Multi"],
    tag: "NEW",
    image: "/products/Short sleeve shirt.jpeg",
    description: "Relaxed short-sleeve shirt. Easy summer layering piece or worn open over a tee.",
    available: true,
    pairsWith: [
      { item: "Black Baggy Jeans", reason: "Open shirt over black denim keeps the look casual and effortless." },
      { item: "White Casual Shorts", reason: "Short sleeve shirt and shorts — the go-to summer outfit." },
      { item: "Vintage Puma Cap", reason: "A cap completes the casual summer fit." },
    ],
  },
  {
    id: 29,
    name: "Socks — Red and Blue",
    category: "Accessories",
    subcategory: "Socks",
    price: 2500,
    size: "One Size",
    colours: ["Red", "Blue"],
    tag: "NEW",
    image: "/products/Socks - red and blue.jpeg",
    description: "Bold red and blue crew socks. The detail that pulls a fit together.",
    available: true,
    pairsWith: [
      { item: "Liverpool FC 2006 Jersey", reason: "Red socks with the Liverpool jersey — colour-matched and intentional." },
      { item: "Adidas × FOG Sneakers", reason: "Statement socks peeking out of chunky sneakers adds a finishing touch." },
      { item: "White Casual Shorts", reason: "Bold socks are the colour accent a clean all-white outfit needs." },
    ],
  },
  {
    id: 30,
    name: "Socks",
    category: "Accessories",
    subcategory: "Socks",
    price: 2000,
    size: "One Size",
    colours: ["White"],
    tag: "NEW",
    image: "/products/Socks.jpeg",
    description: "Clean everyday crew socks. The finishing touch to any fit.",
    available: true,
    pairsWith: [
      { item: "Adidas × FOG Sneakers", reason: "Fresh white socks with chunky sneakers — simple and effective." },
      { item: "Black Baggy Jeans", reason: "White socks visible under rolled or cropped black denim — a classic detail." },
      { item: "Red Casual Shorts", reason: "Clean socks with bold shorts keep the look fresh and put-together." },
    ],
  },
  {
    id: 31,
    name: "Stripe T-Shirt",
    category: "Clothing",
    subcategory: "T-shirts",
    price: 7500,
    size: "L",
    colours: ["Multi"],
    tag: "NEW",
    image: "/products/Stripe t-shirt.jpeg",
    description: "Classic stripe tee. Relaxed fit. A wardrobe staple that works with everything.",
    available: true,
    pairsWith: [
      { item: "Black Baggy Jeans", reason: "Stripe tee over black denim — the simplest and most reliable fit." },
      { item: "Blue Jeans", reason: "Stripe and denim is a classic pairing with a timeless French-inspired edge." },
      { item: "Pink MLB Cap", reason: "A cap adds a sporty finishing touch to the stripe tee." },
    ],
  },
  {
    id: 32,
    name: "Super Baggy Sweatpants in Grey",
    category: "Clothing",
    subcategory: "Sweatpants",
    price: 11000,
    size: "L",
    waist: 'W28"–40"',
    length: 'L32"',
    elasticWaist: true,
    colours: ["Grey"],
    tag: "NEW",
    image: "/products/Super baggy sweatpants in grey.jpeg",
    description: "Extra wide-leg grey sweatpants. Drawstring elastic waist. Maximum volume, maximum comfort.",
    available: true,
    pairsWith: [
      { item: "Light Grey Sweatshirt", reason: "Full grey co-ord in an oversized silhouette — the boldest relaxed look in the drop." },
      { item: "Graphic T-Shirt in Smoke", reason: "Tonal grey tee and super baggy sweats. Effortlessly layered." },
      { item: "Adidas × FOG Sneakers", reason: "Chunky sneakers under super baggy sweats — the proportions are everything." },
    ],
  },
  {
    id: 33,
    name: "Thick Flannel Shirt",
    category: "Clothing",
    subcategory: "Shirts",
    price: 11500,
    size: "L",
    colours: ["Multi"],
    tag: "NEW",
    image: "/products/Thich flannel shirt.jpeg",
    description: "Heavy-weight flannel shirt. Warm and structured. Wear open as a layer or buttoned up.",
    available: true,
    pairsWith: [
      { item: "Black Baggy Jeans", reason: "Flannel over black denim is a grunge-adjacent look that always delivers." },
      { item: "Graphic White T-Shirt", reason: "Layer the flannel open over a white tee for a classic 90s layering look." },
      { item: "Adidas × FOG Sneakers", reason: "Chunky sneakers under a flannel-and-denim look keeps it modern and street." },
    ],
  },
  {
    id: 34,
    name: "Ushanka Trapper Hat in Purple",
    category: "Accessories",
    subcategory: "Caps and hats",
    price: 7500,
    size: "One Size",
    colours: ["Purple"],
    tag: "NEW",
    image: "/products/Ushanka trapper hat in purple.jpeg",
    description: "Purple ushanka trapper hat. Faux fur lining. A bold colourway for a statement winter look.",
    available: true,
    pairsWith: [
      { item: "Bomber Jacket", reason: "Purple hat over an all-black bomber — the hat is the whole outfit." },
      { item: "Black Baggy Jeans", reason: "Bold accessories work best against simple, dark outfits." },
      { item: "Light Grey Sweatshirt", reason: "The purple hat against a grey co-ord is an unexpected but sharp colour pop." },
    ],
  },
  {
    id: 35,
    name: "White Short Sleeve Shirt",
    category: "Clothing",
    subcategory: "Shirts",
    price: 8000,
    size: "M",
    colours: ["White"],
    tag: "NEW",
    image: "/products/White short sleeve shirt.jpeg",
    description: "Crisp white short-sleeve shirt. Clean cut. A versatile summer essential.",
    available: true,
    pairsWith: [
      { item: "Blue Jeans", reason: "White shirt and blue denim is the most dependable smart-casual outfit." },
      { item: "Black Baggy Jeans", reason: "White shirt over black baggy denim keeps the look crisp and intentional." },
      { item: "Pink MLB Cap", reason: "A pop of pink against the white shirt — easy and fresh." },
    ],
  },
];

export const CATEGORIES = {
  Clothing: ["Jackets", "T-shirts", "Shirts", "Jerseys", "Cargo pants", "Jeans", "Shorts", "Track suits", "Trackpants", "Sweatpants", "Sweatshirts", "Hoodies"],
  Accessories: ["Caps and hats", "Socks", "Ties", "Beanies", "Gloves"],
  Shoes: ["Clogs", "Slippers", "Sneakers", "Sandals"],
};

export const POPULAR_SEARCHES = [
  "Sweatpants", "Rugby polo shirt", "Henley t-shirt", "Jeans", "Oversized tee", "Jersey", "Trackpants", "Plain t-shirt", "Raglan t-shirt",
];

export function getProduct(id: number): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getProductByName(name: string): Product | undefined {
  return PRODUCTS.find((p) => p.name === name);
}
