export type Product = {
  id: number;
  name: string;
  category: string;
  subcategory: string;
  price: number;
  sizes: string[];
  colours: string[];
  tag: "NEW" | "2 LEFT" | "1 LEFT" | "SOLD OUT";
  image: string;
  description: string;
  available: boolean;
};

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Inter Milan Lautaro #10 Jersey",
    category: "Clothing",
    subcategory: "T-shirts",
    price: 14500,
    sizes: ["S", "M", "L", "XL"],
    colours: ["Blue", "Black"],
    tag: "NEW",
    image: "/products/lautaro inter milan jersey.jpeg",
    description: "Iconic Inter Milan home jersey featuring Lautaro Martínez #10. Python-print design, Lenovo sponsor. Good-as-new condition.",
    available: true,
  },
  {
    id: 2,
    name: "Liverpool FC 2006 Jersey",
    category: "Clothing",
    subcategory: "T-shirts",
    price: 12500,
    sizes: ["S", "M", "L"],
    colours: ["Red", "White"],
    tag: "2 LEFT",
    image: "/products/liverpool 2006 jersey.jpeg",
    description: "Classic Liverpool FC 2006 home kit. Adidas. Carlsberg sponsor. A collector's piece in great condition.",
    available: true,
  },
  {
    id: 3,
    name: "Burgundy Vintage Windbreaker",
    category: "Clothing",
    subcategory: "Jackets",
    price: 18000,
    sizes: ["M"],
    colours: ["Burgundy", "White", "Blue"],
    tag: "NEW",
    image: "/products/burgundy wind breaker jacket.jpeg",
    description: "Retro Nassau windbreaker in bold burgundy. Striking graphic panelling, full zip, lightweight feel. Perfect for the drop.",
    available: true,
  },
  {
    id: 4,
    name: "Bomber Jacket",
    category: "Clothing",
    subcategory: "Jackets",
    price: 16500,
    sizes: ["M", "L"],
    colours: ["Black"],
    tag: "NEW",
    image: "/products/bomber jacket.jpeg",
    description: "Clean, minimal bomber. Streetwear staple. Versatile enough for any fit.",
    available: true,
  },
  {
    id: 5,
    name: "Navy Blue Quarter-Zip Sweatshirt",
    category: "Clothing",
    subcategory: "Track suits",
    price: 13500,
    sizes: ["M"],
    colours: ["Navy", "White"],
    tag: "1 LEFT",
    image: "/products/navy blue sweatshirt.jpeg",
    description: "Outlier 1991 RC Rider Supply Co. quarter-zip. Navy/white colourblock. Collegiate aesthetic. One left — move fast.",
    available: true,
  },
  {
    id: 6,
    name: "Light Grey Sweatshirt",
    category: "Clothing",
    subcategory: "Track suits",
    price: 12000,
    sizes: ["S", "M"],
    colours: ["Grey"],
    tag: "NEW",
    image: "/products/light grey sweatshirt.jpeg",
    description: "Relaxed-fit light grey crewneck. Everyday comfort, clean silhouette.",
    available: true,
  },
  {
    id: 7,
    name: "Classic Polo Shirt",
    category: "Clothing",
    subcategory: "Shirts",
    price: 9000,
    sizes: ["M", "L", "XL"],
    colours: ["White"],
    tag: "NEW",
    image: "/products/polo shirt.jpeg",
    description: "Crisp polo shirt. Timeless cut. Great for layering or wearing standalone.",
    available: true,
  },
  {
    id: 8,
    name: "Navy Stripe Oversized Tee",
    category: "Clothing",
    subcategory: "T-shirts",
    price: 7500,
    sizes: ["S", "M", "L", "XL", "2XL"],
    colours: ["Navy", "White"],
    tag: "NEW",
    image: "/products/t-shirt.jpeg",
    description: "Boxy navy/white stripe tee. Heavy cotton. Worn oversized or tucked — both work.",
    available: true,
  },
  {
    id: 9,
    name: "Red Casual Shorts",
    category: "Clothing",
    subcategory: "Shorts",
    price: 6500,
    sizes: ["S", "M", "L", "XL"],
    colours: ["Red"],
    tag: "NEW",
    image: "/products/red casual short.jpeg",
    description: "Easy-wearing red shorts. Comfortable fit. Perfect for warmer days.",
    available: true,
  },
  {
    id: 10,
    name: "White Casual Shorts",
    category: "Clothing",
    subcategory: "Shorts",
    price: 6500,
    sizes: ["S", "M", "L"],
    colours: ["White"],
    tag: "NEW",
    image: "/products/white casual short.jpeg",
    description: "Minimal white shorts. Clean look. Pairs with everything.",
    available: true,
  },
  {
    id: 11,
    name: "Black Baggy Jeans",
    category: "Clothing",
    subcategory: "Jeans",
    price: 15000,
    sizes: ["30", "32", "34"],
    colours: ["Black"],
    tag: "NEW",
    image: "/products/black baggy jeans.jpeg",
    description: "Wide-leg black denim with a relaxed, barrel-leg silhouette. Drawstring hem. Statement piece.",
    available: true,
  },
  {
    id: 12,
    name: "Blue Jeans",
    category: "Clothing",
    subcategory: "Jeans",
    price: 13000,
    sizes: ["30", "32", "34", "36"],
    colours: ["Blue"],
    tag: "NEW",
    image: "/products/blue jeans.jpeg",
    description: "Classic blue denim. Straight fit. Goes with everything in the wardrobe.",
    available: true,
  },
  {
    id: 13,
    name: "Black Sweatpants",
    category: "Clothing",
    subcategory: "Sweatpants",
    price: 9000,
    sizes: ["S", "M", "L", "XL"],
    colours: ["Black"],
    tag: "NEW",
    image: "/products/black sweatpants.jpeg",
    description: "Essential black sweatpants. Comfortable, relaxed fit for everyday wear.",
    available: true,
  },
  {
    id: 14,
    name: "Grey Acid Wash Sweatpants",
    category: "Clothing",
    subcategory: "Sweatpants",
    price: 9500,
    sizes: ["S", "M", "L", "XL"],
    colours: ["Grey"],
    tag: "NEW",
    image: "/products/greys weatpants.jpeg",
    description: "Washed grey sweatpants with a vintage, faded look. Wide leg. Drawstring waist.",
    available: true,
  },
  {
    id: 15,
    name: "Vintage Puma Cap",
    category: "Accessories",
    subcategory: "Caps and hats",
    price: 5000,
    sizes: ["One Size"],
    colours: ["Red"],
    tag: "NEW",
    image: "/products/puma cap.jpeg",
    description: "Vintage Puma 6-panel cap in red corduroy. Original tags still on. Rare find.",
    available: true,
  },
  {
    id: 16,
    name: "Pink MLB Cap",
    category: "Accessories",
    subcategory: "Caps and hats",
    price: 5500,
    sizes: ["One Size"],
    colours: ["Pink"],
    tag: "NEW",
    image: "/products/pink MLB cap.jpeg",
    description: "MLB-style pink cap. Clean embroidery. Adjustable strap.",
    available: true,
  },
  {
    id: 17,
    name: "Adidas × FOG Sneakers",
    category: "Shoes",
    subcategory: "Sneakers",
    price: 28000,
    sizes: ["40", "41", "42", "43", "44"],
    colours: ["White", "Grey"],
    tag: "NEW",
    image: "/products/adidas x fog sneakers.jpeg",
    description: "Adidas Fear of God collaboration. Chunky sole, premium materials. Limited and hard to find.",
    available: true,
  },
];

export const CATEGORIES = {
  Clothing: ["Jackets", "T-shirts", "Shirts", "Cargo pants", "Jeans", "Shorts", "Track suits", "Sweatpants"],
  Accessories: ["Caps and hats", "Ties", "Beanies", "Gloves"],
  Shoes: ["Clogs", "Slippers", "Sneakers", "Sandals"],
};

export const POPULAR_SEARCHES = [
  "Liverpool jersey", "Windbreaker", "Baggy jeans", "Puma cap", "Sweatpants", "Oversized tee",
];

export function getProduct(id: number): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
