-- ============================================================
-- Thrift Collision — Product Seed Data
-- Migration: 002_seed_products.sql
-- Run AFTER 001_initial_schema.sql
-- ============================================================

insert into public.products
  (id, name, category, subcategory, price, size, waist, length, elastic_waist, colours, tag, image, description, available, pairs_with)
values

(1, 'Inter Milan Lautaro #10 Jersey', 'Clothing', 'T-shirts', 14500, 'L',
 null, null, false, ARRAY['Blue','Black'], 'NEW',
 '/products/lautaro inter milan jersey.jpeg',
 'Iconic Inter Milan home jersey featuring Lautaro Martínez #10. Python-print design, Lenovo sponsor. Good-as-new condition.',
 true,
 '[{"item":"Black Baggy Jeans","reason":"The contrast between the bold blue jersey and black denim keeps the fit clean and grounded."},{"item":"Grey Acid Wash Sweatpants","reason":"A relaxed, tonal pairing. Grey neutralises the jersey''s colour without competing with it."},{"item":"Adidas × FOG Sneakers","reason":"Chunky white sneakers add weight to the bottom of the fit and balance the oversized jersey top."}]'),

(2, 'Liverpool FC 2006 Jersey', 'Clothing', 'T-shirts', 12500, 'M',
 null, null, false, ARRAY['Red','White'], '2 LEFT',
 '/products/liverpool 2006 jersey.jpeg',
 'Classic Liverpool FC 2006 home kit. Adidas. Carlsberg sponsor. A collector''s piece in great condition.',
 true,
 '[{"item":"Black Baggy Jeans","reason":"Black denim lets the red jersey do the talking. A timeless combo."},{"item":"Black Sweatpants","reason":"Keeps the vibe relaxed and street-ready — jersey as a statement piece."},{"item":"Vintage Puma Cap","reason":"The red cap pulls colour from the jersey and ties the whole look together."}]'),

(3, 'Burgundy Vintage Windbreaker', 'Clothing', 'Jackets', 18000, 'M',
 null, null, false, ARRAY['Burgundy','White','Blue'], 'NEW',
 '/products/burgundy wind breaker jacket.jpeg',
 'Retro Nassau windbreaker in bold burgundy. Striking graphic panelling, full zip, lightweight feel. Perfect for the drop.',
 true,
 '[{"item":"Black Baggy Jeans","reason":"Burgundy over black is a classic contrast — the baggier the jeans, the better the silhouette."},{"item":"Navy Stripe Oversized Tee","reason":"Layer the tee underneath with it slightly visible at the hem for that 90s layering look."},{"item":"Adidas × FOG Sneakers","reason":"The clean white sneaker base grounds the bold jacket colour palette."}]'),

(4, 'Bomber Jacket', 'Clothing', 'Jackets', 16500, 'L',
 null, null, false, ARRAY['Black'], 'NEW',
 '/products/bomber jacket.jpeg',
 'Clean, minimal bomber. Streetwear staple. Versatile enough for any fit.',
 true,
 '[{"item":"Navy Stripe Oversized Tee","reason":"The stripe tee adds visual interest under the bomber without breaking the clean black palette."},{"item":"Black Baggy Jeans","reason":"Full black monochrome. Simple, sharp, and effective."},{"item":"Pink MLB Cap","reason":"A pop of pink cuts through the all-black and adds personality to the fit."}]'),

(5, 'Navy Blue Quarter-Zip Sweatshirt', 'Clothing', 'Track suits', 13500, 'M',
 null, null, false, ARRAY['Navy','White'], '1 LEFT',
 '/products/navy blue sweatshirt.jpeg',
 'Outlier 1991 RC Rider Supply Co. quarter-zip. Navy/white colourblock. Collegiate aesthetic. One left — move fast.',
 true,
 '[{"item":"Blue Jeans","reason":"Tonal navy-on-blue denim is a smart, understated pairing with a collegiate edge."},{"item":"Black Baggy Jeans","reason":"The dark contrast between navy top and black jeans keeps the look clean and structured."},{"item":"Adidas × FOG Sneakers","reason":"White sneakers lift the navy colour and keep the collegiate energy going."}]'),

(6, 'Light Grey Sweatshirt', 'Clothing', 'Track suits', 12000, 'S',
 null, null, false, ARRAY['Grey'], 'NEW',
 '/products/light grey sweatshirt.jpeg',
 'Relaxed-fit light grey crewneck. Everyday comfort, clean silhouette.',
 true,
 '[{"item":"Black Baggy Jeans","reason":"A grey/black combo is the most versatile everyday fit — it always works."},{"item":"Grey Acid Wash Sweatpants","reason":"Tonal grey matching top and bottom for that clean, intentional streetwear look."},{"item":"Vintage Puma Cap","reason":"The red cap pops against grey for a confident colour accent."}]'),

(7, 'Classic Polo Shirt', 'Clothing', 'Shirts', 9000, 'L',
 null, null, false, ARRAY['White'], 'NEW',
 '/products/polo shirt.jpeg',
 'Crisp polo shirt. Timeless cut. Great for layering or wearing standalone.',
 true,
 '[{"item":"Blue Jeans","reason":"White polo and blue denim is a classic smart-casual combination that never ages."},{"item":"Black Baggy Jeans","reason":"White over black is sharp — the polo tucks for a cleaner look or worn loose for streetwear."},{"item":"Adidas × FOG Sneakers","reason":"The chunky white sneakers match the polo''s clean white and elevate the full look."}]'),

(8, 'Navy Stripe Oversized Tee', 'Clothing', 'T-shirts', 7500, 'XL',
 null, null, false, ARRAY['Navy','White'], 'NEW',
 '/products/Stripe t-shirt.jpeg',
 'Boxy navy/white stripe tee. Heavy cotton. Worn oversized or tucked — both work.',
 true,
 '[{"item":"Black Baggy Jeans","reason":"The stripe tee is a statement on its own — let the black jeans stay out of the way."},{"item":"Grey Acid Wash Sweatpants","reason":"Relaxed tee with relaxed sweats. Laid-back energy, intentional look."},{"item":"Pink MLB Cap","reason":"A soft pink cap adds warmth and contrast to the cool navy/white stripe palette."}]'),

(9, 'Red Casual Shorts', 'Clothing', 'Shorts', 6500, 'M',
 'W32"', 'L19"', false, ARRAY['Red'], 'NEW',
 '/products/red casual short.jpeg',
 'Easy-wearing red shorts. Comfortable fit. Perfect for warmer days.',
 true,
 '[{"item":"Navy Stripe Oversized Tee","reason":"The stripe tee''s navy picks up on the red shorts'' boldness for a colour-blocked summer look."},{"item":"Classic Polo Shirt","reason":"White polo and red shorts is a clean, sporty combination."},{"item":"Adidas × FOG Sneakers","reason":"White chunky sneakers complete the bold colour scheme without adding more colour."}]'),

(10, 'White Casual Shorts', 'Clothing', 'Shorts', 6500, 'S',
 'W28"', 'L18"', false, ARRAY['White'], 'NEW',
 '/products/white casual short.jpeg',
 'Minimal white shorts. Clean look. Pairs with everything.',
 true,
 '[{"item":"Inter Milan Lautaro #10 Jersey","reason":"White shorts let the jersey pop without competition. Classic football-inspired look."},{"item":"Light Grey Sweatshirt","reason":"White and grey is effortlessly minimal — an easy go-to pairing."},{"item":"Vintage Puma Cap","reason":"The red cap adds colour to the all-white/grey outfit and finishes it off."}]'),

(11, 'Black Baggy Jeans', 'Clothing', 'Jeans', 15000, '32',
 'W32"', 'L30"', false, ARRAY['Black'], 'NEW',
 '/products/black baggy jeans.jpeg',
 'Wide-leg black denim with a relaxed, barrel-leg silhouette. Drawstring hem. Statement piece.',
 true,
 '[{"item":"Burgundy Vintage Windbreaker","reason":"The bold jacket over clean black denim is a textbook streetwear combination."},{"item":"Bomber Jacket","reason":"All-black top and bottom with a bomber creates a sleek, put-together silhouette."},{"item":"Adidas × FOG Sneakers","reason":"Chunky white sneakers under baggy black jeans creates the perfect proportional contrast."}]'),

(12, 'Blue Jeans', 'Clothing', 'Jeans', 13000, '32',
 'W32"', 'L30"', false, ARRAY['Blue'], 'NEW',
 '/products/blue jeans.jpeg',
 'Classic blue denim. Straight fit. Goes with everything in the wardrobe.',
 true,
 '[{"item":"Classic Polo Shirt","reason":"White polo and blue jeans is timeless. Smart, clean, and versatile."},{"item":"Navy Blue Quarter-Zip Sweatshirt","reason":"Tonal navy and denim blue is a cohesive, put-together look."},{"item":"Adidas × FOG Sneakers","reason":"Chunky sneakers with straight blue denim creates a modern silhouette."}]'),

(13, 'Black Sweatpants', 'Clothing', 'Sweatpants', 9000, 'L',
 'W30"–38"', 'L30"', true, ARRAY['Black'], 'NEW',
 '/products/black sweatpants.jpeg',
 'Essential black sweatpants. Drawstring elastic waist. Comfortable, relaxed fit for everyday wear.',
 true,
 '[{"item":"Liverpool FC 2006 Jersey","reason":"Red jersey over black sweats is easy and expressive — a classic combination."},{"item":"Light Grey Sweatshirt","reason":"Grey top and black bottoms is the foundation of a clean athleisure look."},{"item":"Vintage Puma Cap","reason":"The red cap adds a colour punch to a neutral black-and-grey outfit."}]'),

(14, 'Grey Acid Wash Sweatpants', 'Clothing', 'Sweatpants', 9500, 'M',
 'W28"–36"', 'L29"', true, ARRAY['Grey'], 'NEW',
 '/products/greys weatpants.jpeg',
 'Washed grey sweatpants with a vintage, faded look. Wide leg. Drawstring elastic waist.',
 true,
 '[{"item":"Inter Milan Lautaro #10 Jersey","reason":"The washed grey tones down the jersey''s colour intensity for a balanced, relaxed look."},{"item":"Light Grey Sweatshirt","reason":"Full grey co-ord. When tones match, the intentionality comes through."},{"item":"Adidas × FOG Sneakers","reason":"White sneakers under grey washed sweats lifts the overall look."}]'),

(15, 'Vintage Puma Cap', 'Accessories', 'Caps and hats', 5000, 'One Size',
 null, null, false, ARRAY['Red'], 'NEW',
 '/products/puma cap.jpeg',
 'Vintage Puma 6-panel cap in red corduroy. Original tags still on. Rare find.',
 true,
 '[{"item":"Light Grey Sweatshirt","reason":"The red cap pops against grey and adds the finishing colour accent the outfit needs."},{"item":"Black Sweatpants","reason":"Red cap over a neutral fit injects personality without changing the whole vibe."},{"item":"Navy Stripe Oversized Tee","reason":"The warmth of the red cap contrasts nicely with the cool navy/white stripe palette."}]'),

(16, 'Pink MLB Cap', 'Accessories', 'Caps and hats', 5500, 'One Size',
 null, null, false, ARRAY['Pink'], 'NEW',
 '/products/pink MLB cap.jpeg',
 'MLB-style pink cap. Clean embroidery. Adjustable strap.',
 true,
 '[{"item":"Bomber Jacket","reason":"Pink against all-black adds an unexpected but intentional pop of colour."},{"item":"Navy Stripe Oversized Tee","reason":"The softness of pink plays off the bold navy/white stripe for a balanced look."},{"item":"White Casual Shorts","reason":"White shorts keep the focus upward on the colourful cap and top."}]'),

(17, 'Adidas × FOG Sneakers', 'Shoes', 'Sneakers', 28000, '42',
 null, null, false, ARRAY['White','Grey'], 'NEW',
 '/products/adidas x fog sneakers.jpeg',
 'Adidas Fear of God collaboration. Chunky sole, premium materials. Limited and hard to find.',
 true,
 '[{"item":"Black Baggy Jeans","reason":"The contrast between the white chunky sole and black denim is one of the best sneaker pairings in streetwear."},{"item":"Grey Acid Wash Sweatpants","reason":"Wide leg sweats and chunky sneakers are made for each other — proportions are perfect."},{"item":"Navy Blue Quarter-Zip Sweatshirt","reason":"The white base of the sneakers picks up the white panels in the quarter-zip for a cohesive look."}]'),

(18, 'Baggy Flared Sweatpants in Grey', 'Clothing', 'Sweatpants', 10500, 'M',
 'W28"–36"', 'L31"', true, ARRAY['Grey'], 'NEW',
 '/products/Baggy flared sweatpants in grey.jpeg',
 'Wide-leg flared sweatpants in grey. Drawstring elastic waist. A statement silhouette with effortless comfort.',
 true,
 '[{"item":"Light Grey Sweatshirt","reason":"Full grey co-ord with a flared leg. Intentional and clean."},{"item":"Inter Milan Lautaro #10 Jersey","reason":"Bold jersey over flared sweats — streetwear energy, top to bottom."},{"item":"Adidas × FOG Sneakers","reason":"Chunky sneakers peek out under the flare for the perfect finish."}]'),

(19, 'Baggy Blue Jeans', 'Clothing', 'Jeans', 14000, '32',
 'W32"', 'L30"', false, ARRAY['Blue'], 'NEW',
 '/products/Baggy jeans blue.jpeg',
 'Relaxed baggy blue denim. Wide-leg fit with a worn-in wash. A versatile drop essential.',
 true,
 '[{"item":"Classic Polo Shirt","reason":"Baggy jeans and a polo is a timeless smart-casual combination."},{"item":"Burgundy Vintage Windbreaker","reason":"The bold jacket over loose blue denim is a textbook 90s layering move."},{"item":"Adidas × FOG Sneakers","reason":"Chunky sneakers under baggy denim — the silhouette speaks for itself."}]'),

(20, 'Brown Leather Jacket (M)', 'Clothing', 'Jackets', 32000, 'M',
 null, null, false, ARRAY['Brown'], 'NEW',
 '/products/Brown leather jacket - M.jpeg',
 'Genuine brown leather jacket. Clean minimal cut. A rare thrift find in excellent condition.',
 true,
 '[{"item":"Black Baggy Jeans","reason":"Brown leather over black denim is one of the most timeless combinations in menswear."},{"item":"Navy Stripe Oversized Tee","reason":"The casual tee softens the jacket for a relaxed but put-together look."},{"item":"Adidas × FOG Sneakers","reason":"White chunky sneakers modernise the leather jacket and keep it street-ready."}]'),

(21, 'Brown Leather Jacket (L–XL)', 'Clothing', 'Jackets', 32000, 'L–XL',
 null, null, false, ARRAY['Brown'], 'NEW',
 '/products/Brown leather jacket L-XL.jpeg',
 'Genuine brown leather jacket in a larger cut. Relaxed oversized fit. Premium condition — a serious find.',
 true,
 '[{"item":"Black Baggy Jeans","reason":"Brown leather over black denim is one of the most timeless combinations in menswear."},{"item":"Blue Jeans","reason":"Classic blue denim lets the leather jacket take centre stage."},{"item":"Adidas × FOG Sneakers","reason":"White chunky sneakers modernise the leather jacket and keep it street-ready."}]'),

(22, 'Celtics Basketball Jersey', 'Clothing', 'T-shirts', 13000, 'L',
 null, null, false, ARRAY['Green','White'], 'NEW',
 '/products/Celtics basketball jersey.jpeg',
 'Boston Celtics NBA basketball jersey. Classic green colourway. Great condition.',
 true,
 '[{"item":"Black Baggy Jeans","reason":"The green jersey pops over black denim — clean contrast, no competition."},{"item":"Black Sweatpants","reason":"Jersey and sweats is the quintessential relaxed streetwear combination."},{"item":"Adidas × FOG Sneakers","reason":"White sneakers pick up the jersey''s white accents and complete the look."}]'),

(23, 'Graphic Camo Cap in Red', 'Accessories', 'Caps and hats', 5500, 'One Size',
 null, null, false, ARRAY['Red','Camo'], 'NEW',
 '/products/Graphic camo cap in red.jpeg',
 'Bold red camo graphic cap. Six-panel structured fit. Adjustable strap. A statement accessory.',
 true,
 '[{"item":"Black Baggy Jeans","reason":"The bold cap over a simple black fit lets the accessory do all the talking."},{"item":"Navy Stripe Oversized Tee","reason":"Red camo cap with a navy/white stripe tee — colour-blocked and intentional."},{"item":"Bomber Jacket","reason":"The graphic cap breaks up the clean all-black bomber outfit perfectly."}]'),

(24, 'Graphic T-Shirt in Smoke', 'Clothing', 'T-shirts', 8000, 'L',
 null, null, false, ARRAY['Grey','Black'], 'NEW',
 '/products/Graphic t-shirt in smoke.jpeg',
 'Oversized graphic tee in a smoked grey wash. Heavy cotton. Worn-in feel from day one.',
 true,
 '[{"item":"Black Baggy Jeans","reason":"Smoke tee over black denim — a washed, muted palette that works every time."},{"item":"Grey Acid Wash Sweatpants","reason":"Tonal grey-on-grey with different textures. Understated and intentional."},{"item":"Vintage Puma Cap","reason":"The red cap cuts through the muted palette and adds the finishing touch."}]'),

(25, 'Graphic White T-Shirt', 'Clothing', 'T-shirts', 7500, 'M',
 null, null, false, ARRAY['White'], 'NEW',
 '/products/Graphic white t-shirt.jpeg',
 'Clean white graphic tee. Boxy fit. A versatile base layer or standalone statement.',
 true,
 '[{"item":"Black Baggy Jeans","reason":"White tee and black jeans is the most dependable fit in streetwear."},{"item":"Bomber Jacket","reason":"White graphic tee layered under a black bomber — sharp and easy."},{"item":"Blue Jeans","reason":"White over blue denim is a classic that never ages."}]'),

(26, 'Puffy Gilet in Navy Blue', 'Clothing', 'Jackets', 15000, 'L',
 null, null, false, ARRAY['Navy'], 'NEW',
 '/products/Puffy gilet in navy blue.jpeg',
 'Quilted navy puffer gilet. Lightweight and warm. Perfect for layering over tees or hoodies.',
 true,
 '[{"item":"Navy Stripe Oversized Tee","reason":"Layer the gilet over the tee for a tonal navy look with added depth."},{"item":"Black Baggy Jeans","reason":"Navy gilet over black denim is clean and versatile — a go-to combo."},{"item":"Adidas × FOG Sneakers","reason":"Chunky white sneakers ground the layered navy look."}]'),

(27, 'Realtree Ushanka Trapper Hat', 'Accessories', 'Caps and hats', 8000, 'One Size',
 null, null, false, ARRAY['Camo','Brown'], 'NEW',
 '/products/Realtree ushanka : trapper hat.jpeg',
 'Realtree camo ushanka trapper hat. Faux fur lining. Ear flaps. A statement winter piece.',
 true,
 '[{"item":"Bomber Jacket","reason":"Camo trapper over a black bomber is an unexpected but striking layered look."},{"item":"Brown Leather Jacket (L–XL)","reason":"Earth tones head to toe — the camo hat and brown leather are made for each other."},{"item":"Black Baggy Jeans","reason":"The statement hat does the heavy lifting — keep the bottom simple with black denim."}]'),

(28, 'Short Sleeve Shirt', 'Clothing', 'Shirts', 8500, 'L',
 null, null, false, ARRAY['Multi'], 'NEW',
 '/products/Short sleeve shirt.jpeg',
 'Relaxed short-sleeve shirt. Easy summer layering piece or worn open over a tee.',
 true,
 '[{"item":"Black Baggy Jeans","reason":"Open shirt over black denim keeps the look casual and effortless."},{"item":"White Casual Shorts","reason":"Short sleeve shirt and shorts — the go-to summer outfit."},{"item":"Vintage Puma Cap","reason":"A cap completes the casual summer fit."}]'),

(29, 'Socks — Red and Blue', 'Accessories', 'Socks', 2500, 'One Size',
 null, null, false, ARRAY['Red','Blue'], 'NEW',
 '/products/Socks - red and blue.jpeg',
 'Bold red and blue crew socks. The detail that pulls a fit together.',
 true,
 '[{"item":"Liverpool FC 2006 Jersey","reason":"Red socks with the Liverpool jersey — colour-matched and intentional."},{"item":"Adidas × FOG Sneakers","reason":"Statement socks peeking out of chunky sneakers adds a finishing touch."},{"item":"White Casual Shorts","reason":"Bold socks are the colour accent a clean all-white outfit needs."}]'),

(30, 'Socks', 'Accessories', 'Socks', 2000, 'One Size',
 null, null, false, ARRAY['White'], 'NEW',
 '/products/Socks.jpeg',
 'Clean everyday crew socks. The finishing touch to any fit.',
 true,
 '[{"item":"Adidas × FOG Sneakers","reason":"Fresh white socks with chunky sneakers — simple and effective."},{"item":"Black Baggy Jeans","reason":"White socks visible under rolled or cropped black denim — a classic detail."},{"item":"Red Casual Shorts","reason":"Clean socks with bold shorts keep the look fresh and put-together."}]'),

(31, 'Stripe T-Shirt', 'Clothing', 'T-shirts', 7500, 'L',
 null, null, false, ARRAY['Multi'], 'NEW',
 '/products/Stripe t-shirt.jpeg',
 'Classic stripe tee. Relaxed fit. A wardrobe staple that works with everything.',
 true,
 '[{"item":"Black Baggy Jeans","reason":"Stripe tee over black denim — the simplest and most reliable fit."},{"item":"Blue Jeans","reason":"Stripe and denim is a classic pairing with a timeless French-inspired edge."},{"item":"Pink MLB Cap","reason":"A cap adds a sporty finishing touch to the stripe tee."}]'),

(32, 'Super Baggy Sweatpants in Grey', 'Clothing', 'Sweatpants', 11000, 'L',
 'W28"–40"', 'L32"', true, ARRAY['Grey'], 'NEW',
 '/products/Super baggy sweatpants in grey.jpeg',
 'Extra wide-leg grey sweatpants. Drawstring elastic waist. Maximum volume, maximum comfort.',
 true,
 '[{"item":"Light Grey Sweatshirt","reason":"Full grey co-ord in an oversized silhouette — the boldest relaxed look in the drop."},{"item":"Graphic T-Shirt in Smoke","reason":"Tonal grey tee and super baggy sweats. Effortlessly layered."},{"item":"Adidas × FOG Sneakers","reason":"Chunky sneakers under super baggy sweats — the proportions are everything."}]'),

(33, 'Thick Flannel Shirt', 'Clothing', 'Shirts', 11500, 'L',
 null, null, false, ARRAY['Multi'], 'NEW',
 '/products/Thich flannel shirt.jpeg',
 'Heavy-weight flannel shirt. Warm and structured. Wear open as a layer or buttoned up.',
 true,
 '[{"item":"Black Baggy Jeans","reason":"Flannel over black denim is a grunge-adjacent look that always delivers."},{"item":"Graphic White T-Shirt","reason":"Layer the flannel open over a white tee for a classic 90s layering look."},{"item":"Adidas × FOG Sneakers","reason":"Chunky sneakers under a flannel-and-denim look keeps it modern and street."}]'),

(34, 'Ushanka Trapper Hat in Purple', 'Accessories', 'Caps and hats', 7500, 'One Size',
 null, null, false, ARRAY['Purple'], 'NEW',
 '/products/Ushanka trapper hat in purple.jpeg',
 'Purple ushanka trapper hat. Faux fur lining. A bold colourway for a statement winter look.',
 true,
 '[{"item":"Bomber Jacket","reason":"Purple hat over an all-black bomber — the hat is the whole outfit."},{"item":"Black Baggy Jeans","reason":"Bold accessories work best against simple, dark outfits."},{"item":"Light Grey Sweatshirt","reason":"The purple hat against a grey co-ord is an unexpected but sharp colour pop."}]'),

(35, 'White Short Sleeve Shirt', 'Clothing', 'Shirts', 8000, 'M',
 null, null, false, ARRAY['White'], 'NEW',
 '/products/White short sleeve shirt.jpeg',
 'Crisp white short-sleeve shirt. Clean cut. A versatile summer essential.',
 true,
 '[{"item":"Blue Jeans","reason":"White shirt and blue denim is the most dependable smart-casual outfit."},{"item":"Black Baggy Jeans","reason":"White shirt over black baggy denim keeps the look crisp and intentional."},{"item":"Pink MLB Cap","reason":"A pop of pink against the white shirt — easy and fresh."}]')

on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  price = excluded.price,
  size = excluded.size,
  waist = excluded.waist,
  length = excluded.length,
  elastic_waist = excluded.elastic_waist,
  colours = excluded.colours,
  tag = excluded.tag,
  image = excluded.image,
  description = excluded.description,
  available = excluded.available,
  pairs_with = excluded.pairs_with,
  updated_at = now();
